Repository UB-ES-2020-Mooving/Mooving, pull requests merged in 2020-11, with the labels that each got.

#73 [US28] [T.1] [T.2] [T.4] Mechanic
  flaskProject/add_data.py
  flaskProject/app.py
  flaskProject/data.db
  flaskProject/models/constantes.py
  flaskProject/models/mechanic_model.py
  flaskProject/models/moto_model.py
  flaskProject/resources/client.py
  flaskProject/resources/login.py
  flaskProject/resources/mechanic.py
Labels: backend

#78 [US12.0][T2] Backend: Endpoints Profile
  flaskProject/add_data.py
  flaskProject/app.py
  flaskProject/models/client_model.py
  flaskProject/models/moto_model.py
  flaskProject/resources/article.py
  flaskProject/resources/client.py
Labels: backend

#128 don't save files in cache
  frontend/public/index.html
Labels: devOps

#140 Td6 t1 break travis built
  .travis.yml
  README.md
  build_frontend.sh
  create_frontend.sh
  move_frontend.sh
Labels: devOps

#142 Us15 t1 client moto reservation
  frontend/src/components/Images/MotodivisorRightWhite.png
  frontend/src/components/MotosClient.vue
  frontend/src/components/clientMoto.vue
Labels: frontend

#138 (us15.0)(t2) backend: moto reservation
  .gitignore
  flaskProject/add_data.py
  flaskProject/app.py
  flaskProject/data.db
  flaskProject/models/client_model.py
  flaskProject/models/constantes.py
  flaskProject/models/moto_model.py
  flaskProject/models/reserved_running_model.py
  flaskProject/resources/reserved_start.py
Labels: backend

#146 Us31 t1 moto page mechanic frontend
  frontend/src/components/MechanicMoto.vue
  frontend/src/components/MotosMechanic.vue
  frontend/src/components/Profile.vue
  frontend/src/components/clientMoto.vue
  frontend/src/router/index.js
Labels: frontend
